# Generated by Django 5.2.9 on 2025-12-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number in E164 format: +998901234567",
                max_length=15,
                null=True,
                unique=True,
            ),
        ),
    ]
