# Generated by Django 5.2.9 on 2025-12-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_options_user_unique_email_when_not_null"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_email_when_not_null",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number in E164 format: +998901234567",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("email__isnull", False), models.Q(("email", ""), _negated=True)
                ),
                fields=("email",),
                name="unique_email_when_not_null",
            ),
        ),
    ]
